module.exports = [
    {
        intent: "weather",
        expressions: [
            {value: "What is the weather like?", trigger: "weather.getCurrent"},
            {value: "What is the weather like today?", trigger: "weather.getCurrent"},
            {value: "What is the weather like tomorrow?", trigger: "weather.getTomorrow"},
            {value: "What is the weather going to be like tomorrow?", trigger: "weather.getTomorrow"},
            {value: "What's the temperature?", trigger: "weather.getCurrentTemp"},
            {value: "What temperature is it?", trigger: "weather.getCurrentTemp"},
            {value: "What's the temperature like tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "What temperature is it going to be tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Is it hot?", trigger: "weather.getCurrentTemp"},
            {value: "Is it warm?", trigger: "weather.getCurrentTemp"},
            {value: "Is it cold?", trigger: "weather.getCurrentTemp"},
            {value: "Is it cool?", trigger: "weather.getCurrentTemp"},
            {value: "How hot is it?", trigger: "weather.getCurrentTemp"},
            {value: "How warm is it?", trigger: "weather.getCurrentTemp"},
            {value: "How cool is it?", trigger: "weather.getCurrentTemp"},
            {value: "How cold is it?", trigger: "weather.getCurrentTemp"},
            {value: "Will it be hot tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Will it be cool tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Will it be cold tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Will it be warm tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Is it going to be cold tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Is it going to be cool tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Is it going to be hot tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Is it going to be warm tomorrow?", trigger: "weather.getTomorrowTemp"},
            {value: "Will there be snow tomorrow?", trigger: "weather.getTomorrowConditionSnow"},
            {value: "Is it going to snow tomorrow?", trigger: "weather.getTomorrowConditionSnow"},
            {value: "Will there be snow later this week?", trigger: "weather.getFutureConditionSnow"},
            {value: "Is it going to snow?", trigger: "weather.getFutureConditionSnow"},
            {value: "Is it raining?", trigger: "weather.getCurrentConditionRain"},
            {value: "Do I need an umbrella?", trigger: "weather.getCurrentConditionRain"},
            {value: "Do I need a rain coat?", trigger: "weather.getCurrentConditionRain"},
            {value: "Will there be rain tomorrow?", trigger: "weather.getTomorrowConditionRain"},
            {value: "Is it going to rain tomorrow?", trigger: "weather.getTomorrowConditionRain"},
            {value: "Will I need an umbrella tomorrow?", trigger: "weather.getTomorrowConditionRain"},
            {value: "Will I need a rain coat tomorrow?", trigger: "weather.getTomorrowConditionRain"},
            {value: "Will there be rain later this week?", trigger: "weather.getFutureConditionRain"},
            {value: "Is it going to rain?", trigger: "weather.getFutureConditionRain"}
        ]
    }
];